workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean iOS build
        script: |
          cd ios
          rm -rf Pods Podfile.lock ~/Library/Developer/Xcode/DerivedData
          pod install
          cd ..
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
