workflows:
simulator-workflow:
name: Build for iOs Simulator

environment:
xcode: latest
flutter: stable

groups :
- secret_env

scripts:
- name: Create .env file from Codemagic variables
script: |
echo "API_KEY=$API_KEY" >> .env
echo "BASE_URL=$BASE_URL" >> .env
mv .env ./
echo ".env created

- name: Install Flutter dependencies
script: flutter pub get

- name: Install Pods
script: |
cd ios
pod install
cd ..

- name: Build Flutter for iOs simulator
script: |
flutter build ios -- simulator -- debug

- name: Build iOs Simulator App
script: |
xcodebuild \
-workspace ios/Runner.xcworkspace \
-scheme Runner \
-sdk iphonesimulator \
-configuration Debug \
-destination 'generic/platform=ios Simulator' \
build

artifacts:
- build/ios/iphonesimulator/ ** / *. app