workflows:
  ios-test:
    name: iOS Test
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Run tests
        script: flutter test
      - name: Build iOS app for simulator
        script: |
          set -e
          flutter build ios --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/*.app
    testing:
      ios_simulator:
        xcode_simulator:
          device: "iPhone 14"
          os: "latest"
