// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOpmPNmMBod1IKUcjfRqUQ5tfF6tUGA_g',
    appId: '1:589711254718:web:4dbfbefb0b80201b31aaef',
    messagingSenderId: '589711254718',
    projectId: 'medicinder',
    authDomain: 'medicinder.firebaseapp.com',
    storageBucket: 'medicinder.firebasestorage.app',
    measurementId: 'G-626321YBJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-RlF840gPHsG0FpvVivpZaEAfarY8BzE',
    appId: '1:589711254718:android:1f47aab8ea30484a31aaef',
    messagingSenderId: '589711254718',
    projectId: 'medicinder',
    storageBucket: 'medicinder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM2wyvudO4nJfplMSyWFXEoubbNv8DHQg',
    appId: '1:589711254718:ios:4adb0a817dcdc95931aaef',
    messagingSenderId: '589711254718',
    projectId: 'medicinder',
    storageBucket: 'medicinder.firebasestorage.app',
    iosBundleId: 'com.medora.medicinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM2wyvudO4nJfplMSyWFXEoubbNv8DHQg',
    appId: '1:589711254718:ios:5b28e72726df997e31aaef',
    messagingSenderId: '589711254718',
    projectId: 'medicinder',
    storageBucket: 'medicinder.firebasestorage.app',
    iosBundleId: 'com.example.medicinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOpmPNmMBod1IKUcjfRqUQ5tfF6tUGA_g',
    appId: '1:589711254718:web:7bd03cf3da2b28b131aaef',
    messagingSenderId: '589711254718',
    projectId: 'medicinder',
    authDomain: 'medicinder.firebaseapp.com',
    storageBucket: 'medicinder.firebasestorage.app',
    measurementId: 'G-21RKXTZQL6',
  );
}
