platform :ios, '13.0'

# Locate Flutter SDK and load CocoaPods helper
flutter_root = File.expand_path('..', File.read(File.join(__dir__, 'Flutter', 'Generated.xcconfig')).match(/FLUTTER_ROOT=(.*)/)[1])
require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb'))

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_additional_ios_build_settings(installer)
end
