// Mocks generated by Mockito 5.4.5 from annotations
// in medicinder/test/unit/presentation/cubit/medication_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:medicinder/domain/entities/medication.dart' as _i5;
import 'package:medicinder/domain/repositories/medication_repository.dart'
    as _i2;
import 'package:medicinder/domain/usecases/add_medication.dart' as _i3;
import 'package:medicinder/domain/usecases/delete_medication.dart' as _i8;
import 'package:medicinder/domain/usecases/get_medications.dart' as _i6;
import 'package:medicinder/domain/usecases/reset_daily_doses.dart' as _i9;
import 'package:medicinder/domain/usecases/update_dose_status.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMedicationRepository_0 extends _i1.SmartFake
    implements _i2.MedicationRepository {
  _FakeMedicationRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AddMedication].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddMedication extends _i1.Mock implements _i3.AddMedication {
  MockAddMedication() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MedicationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMedicationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MedicationRepository);

  @override
  _i4.Future<void> call(_i5.Medication? medication) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [medication],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [GetMedications].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMedications extends _i1.Mock implements _i6.GetMedications {
  MockGetMedications() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MedicationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMedicationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MedicationRepository);

  @override
  _i4.Future<List<_i5.Medication>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Medication>>.value(<_i5.Medication>[]),
      ) as _i4.Future<List<_i5.Medication>>);
}

/// A class which mocks [UpdateDoseStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateDoseStatus extends _i1.Mock implements _i7.UpdateDoseStatus {
  MockUpdateDoseStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MedicationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMedicationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MedicationRepository);

  @override
  _i4.Future<void> call(
    String? medicationId,
    int? doseIndex,
    bool? taken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            medicationId,
            doseIndex,
            taken,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [DeleteMedication].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteMedication extends _i1.Mock implements _i8.DeleteMedication {
  MockDeleteMedication() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MedicationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMedicationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MedicationRepository);

  @override
  _i4.Future<void> call(String? medicationId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [medicationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ResetDailyDoses].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetDailyDoses extends _i1.Mock implements _i9.ResetDailyDoses {
  MockResetDailyDoses() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MedicationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMedicationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MedicationRepository);

  @override
  _i4.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
